name: gnn-builder
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyg>=2.3
  - numpy
  - scipy
  - networkx
  - scikit-learn
  - matplotlib
  - pandas
  - seaborn
  - jinja2
  - tqdm
  - joblib
  - rich
  - textual
  - python-dotenv
  - mypy
  - black
  - pylint
  - ruff
  - flake8
  - rdkit
  - pynvml