name: build_docs

on: workflow_dispatch

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U .[docs]

      - name: Build Docs
        run: sphinx-build -b html ./docs/source ./docs/build/

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs/build/
      #     force_orphan: true
